
// This file has been generated by the GUI designer. Do not modify.
namespace BlogUploader
{
	public partial class AuthenticationWindow
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Entry tbOAuthCode;
		private global::Gtk.Button btAuth;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget BlogUploader.AuthenticationWindow
			this.Name = "BlogUploader.AuthenticationWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("AuthenticationWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child BlogUploader.AuthenticationWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.tbOAuthCode = new global::Gtk.Entry ();
			this.tbOAuthCode.CanFocus = true;
			this.tbOAuthCode.Name = "tbOAuthCode";
			this.tbOAuthCode.IsEditable = true;
			this.tbOAuthCode.InvisibleChar = '●';
			this.vbox1.Add (this.tbOAuthCode);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tbOAuthCode]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btAuth = new global::Gtk.Button ();
			this.btAuth.CanFocus = true;
			this.btAuth.Name = "btAuth";
			this.btAuth.UseUnderline = true;
			// Container child btAuth.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-connect", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = global::Mono.Unix.Catalog.GetString ("Autorizar");
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.btAuth.Add (w2);
			this.vbox1.Add (this.btAuth);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btAuth]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.btAuth.Clicked += new global::System.EventHandler (this.btAutenticate_Click);
		}
	}
}
